"""
CBAM report generator for GreenGate.
Generates EU-compatible CBAM report format from calculation results.
"""

import json
from datetime import datetime, timezone
from typing import Any


def generate_cbam_report(
    input_data: dict[str, Any],
    calculation_result: dict[str, Any],
    recommendations: list[dict[str, Any]],
    report_id: str,
    tx_hash: str | None = None,
    report_hash: str | None = None,
) -> dict[str, Any]:
    """
    Generate a complete CBAM-formatted report.

    Args:
        input_data: Original calculation input data.
        calculation_result: Output from EmissionEngine.calculate().
        recommendations: AI-generated recommendations.
        report_id: Unique report identifier.
        tx_hash: Blockchain transaction hash (if certified).
        report_hash: SHA-256 report hash (if certified).

    Returns:
        Complete CBAM report dictionary.
    """
    now = datetime.now(timezone.utc)

    report: dict[str, Any] = {
        "report_metadata": {
            "report_id": report_id,
            "generated_at": now.isoformat(),
            "platform": "GreenGate — AI + Blockchain CBAM Compliance",
            "version": "1.0.0",
            "standard": "EU CBAM Regulation (EU) 2023/956",
        },
        "installation_operator": {
            "company_name": input_data.get("company_name", ""),
            "state": input_data.get("state", ""),
            "country": "India",
            "sector": input_data.get("sector", ""),
            "eu_importer_name": input_data.get("eu_importer_name", ""),
        },
        "production_data": {
            "annual_production_tonnes": input_data.get("annual_production_tonnes", 0),
            "eu_export_tonnes": input_data.get("eu_export_tonnes", 0),
            "reporting_period": f"{now.year - 1}-01-01 to {now.year - 1}-12-31",
        },
        "energy_inputs": {
            "electricity_kwh_per_month": input_data.get("electricity_kwh_per_month", 0),
            "solar_kwh_per_month": input_data.get("solar_kwh_per_month", 0),
            "coal_kg_per_month": input_data.get("coal_kg_per_month", 0),
            "natural_gas_m3_per_month": input_data.get("natural_gas_m3_per_month", 0),
            "diesel_litres_per_month": input_data.get("diesel_litres_per_month", 0),
            "lpg_litres_per_month": input_data.get("lpg_litres_per_month", 0),
            "furnace_oil_litres_per_month": input_data.get(
                "furnace_oil_litres_per_month", 0
            ),
            "biomass_kg_per_month": input_data.get("biomass_kg_per_month", 0),
        },
        "emissions_summary": {
            "scope1_co2_tonnes": calculation_result.get("scope1_co2_tonnes", 0),
            "scope2_co2_tonnes": calculation_result.get("scope2_co2_tonnes", 0),
            "total_co2_tonnes": calculation_result.get("total_co2_tonnes", 0),
            "co2_per_tonne_product": calculation_result.get("co2_per_tonne_product", 0),
            "eu_embedded_co2_tonnes": calculation_result.get(
                "eu_embedded_co2_tonnes", 0
            ),
            "grid_emission_factor_used": calculation_result.get("grid_factor_used", 0),
        },
        "emissions_breakdown": calculation_result.get("breakdown", {}),
        "cbam_assessment": {
            "cbam_liability_eur": calculation_result.get("cbam_liability_eur", 0),
            "cbam_liability_inr": calculation_result.get("cbam_liability_inr", 0),
            "eu_carbon_price_eur_per_tonne": 90.0,
            "vs_sector_benchmark_pct": calculation_result.get("vs_benchmark_pct", 0),
        },
        "recommendations": recommendations,
        "blockchain_verification": {
            "is_certified": tx_hash is not None,
            "report_hash": report_hash,
            "transaction_hash": tx_hash,
            "network": "Polygon Amoy Testnet",
            "verification_url": (
                f"https://amoy.polygonscan.com/tx/{tx_hash}" if tx_hash else None
            ),
        },
        "disclaimer": (
            "This report is generated by GreenGate using IPCC and CEA emission factors. "
            "For official CBAM compliance, please verify with an accredited EU verifier. "
            "Blockchain certification ensures data immutability and tamper-proof storage."
        ),
    }

    return report
